name: Build PDF

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc and dependencies
        run: sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-plain-generic

      - name: Normalize File Paths (Windows to Linux)
        run: sed -i 's|\\|/|g' OrderList.txt

      - name: Create Title Page File
        run: |
          cat <<EOF > titlepage.tex
          \begin{titlepage}
          \begin{center}
          \vspace*{2cm}
          {\Huge \textbf{PortSwigger Academy Notes}} \\[1.5cm]
          {\Large Ludicro} \\[1cm]
          {\large $(date +'%B %d, %Y')} \\[2cm]
          \vfill
          \end{center}
          \end{titlepage}
          EOF

      - name: Create Page Break File
        run: echo "\newpage" > pagebreak.tex

      - name: Generate PDF
        run: |
          pandoc $(cat OrderList.txt) -o Ludicro-PortSwigger.pdf \
            --pdf-engine=xelatex \
            --resource-path=. \
            --include-before-body titlepage.tex \
            --include-before-body pagebreak.tex \
            --toc \
            --toc-depth=2 \
            --metadata graphics=true \
            --metadata geometry="margin=1in" \
            --metadata fontsize="12pt"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: Ludicro-PortSwigger.pdf
